=== zihaowangcmu/libs/src/test/resources/schema/wv.dnp-user-schema.v1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "dnp-user-schema",
  "javaType": "com.tracelink.dnp.user",
  "id": "wv:dnp-user-schema",
  "schemaId": "masterSchema",
  "schemaVersion": 1,
  "objectType": "wv:dnp-user-schema",
  "objectTypeSchemaVersion": 1,
  "objectTypeSchemaSubversion": 1601049928671,
  "javaInterfaces": [
    "com.tracelink.dnp.api.TLObject",
    "com.tracelink.dnp.api.TLPersistence"
  ],
  "definitions" : {
    "dateTimeType": {
      "$id": "#dateTimeType",
      "type": "integer",
      "format": "utc-millisec",
      "description": "date created in Epoch time format"
    },
    "data": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "luceneStore": true
        },
        "age": {
          "type": "number"
        },
        "address": {
          "type": "object",
          "properties": {
            "country": {
              "type": "string",
              "luceneStore": true
            },
            "state": {
              "type": "string"
            },
            "city": {
              "type": "string"
            }
          }
        },
        "birthday": {
          "type": "object",
          "properties": {
            "year": {
              "type": "number"
            },
            "month": {
              "type": "number"
            },
            "day": {
              "type": "number"
            }
          }
        },
        "high-school": {
          "type": "string"
        },
        "college": {
          "type": "string",
          "snippet": "${payload.relationships.aptBusinessObjectAssignedToPartnerMasterData[0].toId}"
        },
        "phones": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "phoneNumberType": {
                "type": "string",
                "luceneStore": true
              },
              "phoneNumberValue": {
                "type": "string",
                "luceneStore": false
              }
            }
          }
        },
        "hobbies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "string"
    },
    "schemaId": {
      "type": "string"
    },
    "schemaVersion": {
      "type": "integer"
    },
    "dataVersion": {
      "type": "integer",
      "description": "version of the data",
      "example": "1"
    },
    "creationDateTime": {
      "type": "number",
      "format": "utc-millisec",
      "description": "date created in ms"
    },
    "lastUpdatedDateTime" : {
      "$ref" : "#/definitions/dateTimeType"
    },
    "description": {
      "type": "string"
    },
    "data" : {
      "$ref" : "#/definitions/data"
    }
  },
  "indexes": [
    {
      "indexName": "index-username",
      "style": "DNP",
      "category": "NORMAL",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "username"
      ]
    },
    {
      "indexName": "index-phones",
      "style": "DNP",
      "category": "SET",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "/data/phones/*/phoneNumberValue"
      ]
    },
    {
      "indexName": "index-hobbies",
      "style": "DNP",
      "category": "SET",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "/data/hobbies/*"
      ]
    },
    {
      "indexName": "index-schools",
      "style": "DNP",
      "category": "SET",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "high-school",
        "college"
      ]
    },
    {
      "indexName": "index-compound-schema",
      "style": "DNP",
      "category": "NORMAL",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "schemaId",
        "schemaVersion"
      ]
    },
    {
      "indexName": "index-lastUpdatedDateTime",
      "category": "NORMAL",
      "dataType": "long",
      "unique": true,
      "asc": true,
      "fields": [
        "/lastUpdatedDateTime"
      ]
    },
    {
      "indexName": "index-wvfts-fields",
      "style": "DNP",
      "category": "WVFTS",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "schemaId",
        "username"
      ]
    },
    {
      "indexName": "index-fts-hobbies",
      "style": "DNP",
      "category": "FTS",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "/data/hobbies/*"
      ]
    },
    {
      "indexName": "index-fts-username",
      "style": "DNP",
      "category": "FTS",
      "dataType": "string",
      "unique": false,
      "asc": true,
      "fields": [
        "username"
      ]
    },
    {
      "indexName": "index-fts-age",
      "style": "DNP",
      "category": "FTS",
      "dataType": "long",
      "unique": false,
      "asc": true,
      "fields": [
        "age"
      ]
    },
    {
      "indexName": "index-facet-address",
      "style": "DNP",
      "category": "LUCENE_FACETED",
      "dataType": "string",
      "fields": [
        "/data/address/country",
        "/data/address/state",
        "/data/address/city"
      ]
    },
    {
      "indexName": "index-facet-birthday",
      "style": "DNP",
      "category": "LUCENE_FACETED",
      "dataType": "string",
      "fields": [
        "/data/birthday/year",
        "/data/birthday/month",
        "/data/birthday/day"
      ]
    }
  ]
}

=== zihaowangcmu/libs/src/test/resources/data/dnp-user-2.json
{
  "schemaId": "dnp:user:v1.json",
  "schemaVersion": 1,
  "dataVersion": 0,
  "data": {
    "username": "zihao",
    "age": 99,
    "description": "8b384716-dba7-47cb-9d35-503462b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac",
    "university": "school2",
    "company": "tracelink",
    "address": {
      "country": "US",
      "state": "MA",
      "city": "Boston"
    },
    "birthday": {
      "year": 2020,
      "month": 1,
      "day": 1
    },
    "phones": [
      {
        "phoneNumberType": "cell",
        "phoneNumberValue": "123-456-7890"
      },
      {
        "phoneNumberType": "home",
        "phoneNumberValue": "234-5678-901"
      }
    ],
    "hobbies": [
      "basketball",
      "ski"
    ]
  }
}

=== zihaowangcmu/libs/src/test/resources/data/dnp-user-1.json
{
  "schemaId": "dnp:user:v1.json",
  "schemaVersion": 1,
  "dataVersion": 0,
  "data": {
    "username": "zihao",
    "age": 88,
    "high-school": "school03",
    "description": "8b384716-dba7-47cb-9d35-503462b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac8b384716-dba7-47cb-9d35-503462ab1fac",
    "college": "school2",
    "address": {
      "country": "US",
      "state": "MA",
      "city": "Boston"
    },
    "birthday": {
      "year": 1990,
      "month": 1,
      "day": 1
    },
    "phones": [
      {
        "phoneNumberType": "cell",
        "phoneNumberValue": "123-456-7890"
      },
      {
        "phoneNumberValue": "234-5678-333"
      },
      {
        "phoneNumberType": "home",
        "phoneNumberValue": "234-5678-901"
      }
    ],
    "hobbies": [
      "basketball",
      "ski"
    ]
  }
}
